export const AD_REQUEST = 'AD_REQUEST';
export const AD_ERROR = 'AD_ERROR';
export const AD_SUCCESS = 'AD_SUCCESS';

// youtube
export const YOUTUBE_SEARCH_INIT_REQUEST = 'YOUTUBE_SEARCH_INIT_REQUEST';
export const YOUTUBE_SEARCH_INIT_SUCCESS = 'YOUTUBE_SEARCH_INIT_SUCCESS';
export const YOUTUBE_SEARCH_INIT_ERROR = 'YOUTUBE_SEARCH_INIT_ERROR';

export const YOUTUBE_SEARCH_BAR_SIZE_CHANGE = 'YOUTUBE_SEARCH_BAR_SIZE_CHANGE';
